config/routes.rb
Rails.application.routes.draw do
  resources :listeneds do
    collection do
      post :search, action: :index
    end
  end
  root 'listeneds#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listened.rb
# coding: utf-8

# == Schema Information
#
# Table name: listeneds
#
#  id            :bigint           not null, primary key
#  created_by    :integer
#  deleted_at    :datetime
#  deleted_by    :integer
#  listen_at     :datetime
#  listen_origin :string
#  listen_words  :string
#  lock_version  :integer          default(0), not null
#  updated_by    :integer
#  value         :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#

require 'google/apis/sheets_v4'
require "googleauth"


class Listened < ApplicationRecord
  SHEET_ID = "15uqxj5YSYxbc-wK7hi-b65GrrT9n-0eJ8hNXfhBsiqE"
  COLUMNS = {
    created_at: :A,
    listen_at: :B,
    created_by: :C,
    updated_at: :D,
    updated_by: :E,
    user: :F,
    listen_words: :G,
    value: :H
  }



  def self.google_drive
    credentials = Google::Auth::UserRefreshCredentials.new(
      client_id: ENV['G_CLIENT_ID'],
      client_secret: ENV['G_CLIENT_SECRET'],
      scope: %w(https://www.googleapis.com/auth/drive https://spreadsheets.google.com/feeds/),
      redirect_uri: 'urn:ietf:wg:oauth:2.0:oob'
    )
    credentials.refresh_token = ENV["G_REFRESH_TOKEN"]
    credentials.fetch_access_token!
    GoogleDrive::Session.from_credentials(credentials)
  end

  def self.sheet
    session = self.google_drive
    session.spreadsheet_by_key(SHEET_ID).worksheet_by_title("Listened")
  end

  def self.insert(hash={})
    sheet = self.sheet
    row = sheet.num_rows + 1
    hash.each do |col, val|
      cell = "#{COLUMNS[col.to_sym]}#{row}"
      puts cell
      sheet[cell] = val
    end
    sheet.save
  end

  class Search
    include ActiveModel::Model
    include ActiveModelBase

    attr_accessor :listen_words, :listen_origin, :listen_at_from, :listen_at_to, :user_id_from, :user_id_to, :value_from, :value_to

          type_int :user_id_from, :user_id_to, :value_from, :value_to

    def search(page)
      model = Listened.active



      model = model.between(:user_id, self.user_id_from, self.user_id_to)

      model = model.like(:listen_words, "%#{self.listen_words}%") if self.listen_words.present?

      model = model.like(:listen_origin, "%#{self.listen_origin}%") if self.listen_origin.present?

      model = model.between(:value, self.value_from, self.value_to)

      model.page(page)
    end
  end
end

app/controllers/listeneds_controller.rb
# coding: utf-8
class ListenedsController < ApplicationController
  before_action :set_listened, only: [:show, :edit, :update, :destroy]

  # GET /listeneds
  def index
    @search_listened = Listened::Search.new(search_params)
    @listeneds = @search_listened.search(params[:page])
  end

  # GET /listeneds/1
  def show
  end

  # GET /listeneds/new
  def new
    @listened = Listened.new
  end

  # GET /listeneds/1/edit
  def edit
  end

  # POST /listeneds
  def create
    if Listened.insert(listened_params)
      render plain: :success
    else
      render plain: :failure
    end

    #@listened = Listened.new(listened_params)

#    if @listened.save
#      redirect_to @listened, notice: 'Listened was successfully created.'
#    else
#      render :new
#    end
  end

  # PATCH/PUT /listeneds/1
  def update
    if @listened.update(listened_params)
      redirect_to @listened, notice: 'Listened was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /listeneds/1
  def destroy
    @listened.logical_delete!
    redirect_to listeneds_url, notice: 'Listened was successfully destroyed.'
  end

  private
    # Search params
    def search_params
      if params[:listened_search]
        params.require(:listened_search).permit(:listen_words, :listen_origin, :listen_at_from, :listen_at_to, :user_id_from, :user_id_to, :value_from, :value_to)
      else
        {}
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_listened
      @listened = Listened.active.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def listened_params
      params.require(:listened).permit(:listen_at, :user_id, :listen_words, :listen_origin, :value, :lock_version)
    end
end

app/views/listeneds/_form.html.erb
<%-
only_show ||= false
url =
  if @listened.new_record?
    listeneds_path
  else
    listened_path(@listened)
  end
-%>
<div class="card bg-light mb-3"><div class="card-body">
  <%= simple_form_for(@listened, url: url) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :listen_at,
            disabled: only_show
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :user_id,
            disabled: only_show
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :listen_words,
            disabled: only_show
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :listen_origin,
            disabled: only_show
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :value,
            disabled: only_show
          ) %>
        </div>
      </div>
      <%= f.hidden_field :lock_version %>
    </div>

    <%- unless only_show -%>
      <div class="form-actions row justify-content-around">
        <%= f.button :submit, class: "btn btn-primary col-md-3 col-sm-5" %>
      </div>
    <%- end -%>
  <% end %>
</div></div>

app/views/listeneds/edit.html.erb
<%= render 'form', listened: @listened %>

<div class="row justify-content-around">
  <%= link_to '戻る', listeneds_path, class: "btn btn-secondary col-md-2 col-sm-4" %>
  <%= link_to '削除', listened_path(@listened), method: :delete, data: { confirm: '削除します。よろしいですか？' }, class: 'btn btn-danger col-md-2 col-sm-4'  %>
</div>

app/views/listeneds/index.html.erb
<div class="card bg-light mb-3"><div class="card-body">
  <%= simple_form_for @search_listened, url: search_listeneds_path do |f| %>
    <div class="form-inputs">
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :listen_at,
            as: :date_range
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :user_id,
            as: :int_range
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :listen_words,
          ) %>
        </div>
        <div class="col-md">
          <%= f.input(
            :listen_origin,
          ) %>
        </div>
      </div>
      <div class="row">
        <div class="col-md">
          <%= f.input(
            :value,
            as: :int_range
          ) %>
        </div>
      </div>
    </div>
    <div class="form-actions search d-flex justify-content-end">
      <%= f.button :submit, class: "btn btn-primary col-md-3 col-sm-5", value: "検索" %>
    </div>
  <% end %>
</div></div>

<div class="card bg-light mb-3"><div class="card-body">
  <%- if @listeneds.blank? -%>
    <p><%= t("activerecord.models.listened") %>は登録されていません。</p>
  <%- else -%>
    <div class="text-right">
      <%= page_entries_info @listeneds %>
    </div>
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th><%= Listened.human_attribute_name :listen_at %></th>
            <th><%= Listened.human_attribute_name :user_id %></th>
            <th><%= Listened.human_attribute_name :listen_words %></th>
            <th><%= Listened.human_attribute_name :listen_origin %></th>
            <th><%= Listened.human_attribute_name :value %></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @listeneds.each do |listened| %>
            <tr>
              <td><%= listened.listen_at %></td>
              <td><%= listened.user_id %></td>
              <td><%= listened.listen_words %></td>
              <td><%= listened.listen_origin %></td>
              <td><%= listened.value %></td>
              <td><%= link_to '編集', edit_listened_path(listened), class: 'btn btn-primary btn-block' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row justify-content-around">
      <%= paginate @listeneds %>
    </div>
  <%- end -%>
</div></div>

<div class="row justify-content-around">
  <%= link_to '新規作成', new_listened_path, class: 'btn btn-info col-md-3 col-sm-5' %>
</div>

app/views/listeneds/new.html.erb
<%= render 'form', listened: @listened %>

<div class="row justify-content-around">
  <%= link_to '戻る', listeneds_path, class: "btn btn-secondary col-md-2 col-sm-4" %>
</div>

app/views/listeneds/show.html.erb
<%= render "form", only_show: true %>

<div class="row justify-content-around">
  <%= link_to '戻る', listeneds_path, class: "btn btn-secondary col-md-2 col-sm-4" %>
  <%= link_to '編集', edit_listened_path(@listened), class: 'btn btn-success col-md-2 col-sm-4' %>
</div>